baseURL = "https://www.ujjwalnagar.com"
languageCode = "en-us"
title = "Ujjwal Nagar"
description = "The Blog, project's and everything about Ujjwal Nagar"
theme="archie"
copyright = "© Ujjwal"

#[imaging]
#  [imaging.exif]
#    # (Reverted) Let Hugo auto-rotate images per EXIF so portrait shots display correctly.
#    # DisableRotation = true

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[pagination]
  disableAliases = false
  pagerSize = 3 # articles per page
  path = 'page' 

[params]
	mode="toggle" # color-mode light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle =  "Hi there! I am Ujjwal and you are welcome to my little Nagari (City) on the internet."
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support
  ShowFullTextinRSS = true
  favicon = "/favicon.svg"
  # Main content sections for homepage and related listings
  mainSections = ["writings"]

  # Homepage About content now sourced from content/homepage/about.md (headless bundle)

[sitemap]
  changeFreq = 'weekly'
  disable = false
  filename = 'sitemap.xml'
  priority = -1
  

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/ujjwalishere"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://www.instagram.com/ujjwalnagar08/"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/ujjwal-nagar-india/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1


[[menu.main]]
name = "Writings"
url = "/writings"
weight = 3

[[menu.main]]
name = "Reading"
url = "/reading"
weight = 5

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 2

[[menu.main]]
name = "Creative Corner"
url = "/creative-corner"
weight = 4

[[menu.main]]
name = "Music"
url = "/music"
weight = 6

[[menu.main]]
name = "About Me"
url = "/about"
weight = 7

[[menu.main]]

## Tags menu removed; tag filtering now handled on writings page

#[[menu.main]]
#name = "Tags"
#url = "/tags"
#weight = 4

[[menu.main]]
name = "RSS"
url = "/index.xml"
weight = 8


[markup]
  [markup.goldmark]
    duplicateResourceFiles = false
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      [markup.goldmark.extensions.cjk]
        eastAsianLineBreaks = false
        eastAsianLineBreaksStyle = 'simple'
        enable = false
        escapedSpace = false
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.delete]
          enable = false
        [markup.goldmark.extensions.extras.insert]
          enable = false
        [markup.goldmark.extensions.extras.mark]
          enable = false
        [markup.goldmark.extensions.extras.subscript]
          enable = false
        [markup.goldmark.extensions.extras.superscript]
          enable = false
      [markup.goldmark.extensions.passthrough]
        enable = false
        [markup.goldmark.extensions.passthrough.delimiters]
          block = []
          inline = []
      [markup.goldmark.extensions.typographer]
        apostrophe = '&rsquo;'
        disable = false
        ellipsis = '&hellip;'
        emDash = '&mdash;'
        enDash = '&ndash;'
        leftAngleQuote = '&laquo;'
        leftDoubleQuote = '&ldquo;'
        leftSingleQuote = '&lsquo;'
        rightAngleQuote = '&raquo;'
        rightDoubleQuote = '&rdquo;'
        rightSingleQuote = '&rsquo;'
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      wrapStandAloneImageWithinParagraph = true
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        enableDefault = false
      [markup.goldmark.renderHooks.link]
        enableDefault = false
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[services]
  [services.rss]
    limit = -1
